/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gf.cotos.view;

import com.gf.cotos.controller.Events;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.net.URL;

/**
 *
 * @author ismael
 */
public class LoginView extends JFrame {

    /**
     * Creates new form Login
     */
    public LoginView() {
        initComponents();
        setResizable(false);
        setWindowIcon();
        setLocationRelativeTo(null);
        setLabelImg();
    }

    private void setWindowIcon() {
        URL url = getClass().getResource("/logo.png");
        Image img = new ImageIcon(url).getImage();
        setIconImage(img);
    }

    private void setLabelImg() {
        URL url = getClass().getResource("/logo.png");
        Image img = new ImageIcon(url).getImage()
                .getScaledInstance(lblImg.getHeight(), lblImg.getHeight(), Image.SCALE_SMOOTH);
        lblImg.setIcon(new ImageIcon(img));
        lblImg.setLocation(0,0);
        lblImg.setHorizontalAlignment(JLabel.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtDNI = new JTextField();
        lblDNI = new JLabel();
        lblImg = new JLabel();
        bttIniciarSesion = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de sesión");

        jtDNI.setColumns(9);
        jtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtDNIKeyPressed(evt);
            }
        });

        lblDNI.setFont(new Font("Roboto", 0, 12)); // NOI18N
        lblDNI.setText("Introduce tu DNI:");

        bttIniciarSesion.setText("Iniciar sesión");
        bttIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttIniciarSesionActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblImg, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblDNI)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtDNI, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(bttIniciarSesion, GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImg, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtDNI)
                    .addComponent(lblDNI, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(bttIniciarSesion)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttIniciarSesionActionPerformed
        Events.loginAccepted(jtDNI.getText());
    }//GEN-LAST:event_bttIniciarSesionActionPerformed

    private void jtDNIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDNIKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            bttIniciarSesion.doClick();
    }//GEN-LAST:event_jtDNIKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton bttIniciarSesion;
    private JTextField jtDNI;
    private JLabel lblDNI;
    private JLabel lblImg;
    // End of variables declaration//GEN-END:variables
}
