/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gf.cotos.view;

import com.gf.cotos.controller.Controller;
import com.gf.cotos.controller.Events;
import com.gf.cotos.entities.Coto;
import com.gf.cotos.entities.Usuario;

import javax.swing.*;
import java.awt.*;
import java.net.URL;

/**
 *
 * @author ismael
 */
public class MainView extends JFrame {

    private boolean isCurrentPanelUsuario;

    /**
     * Creates new form Main
     */
    public MainView() {
        initComponents();
        setWindowIcon();
        setName("CaCoCyL");
        setLocationRelativeTo(null);
        setBttUsuarioImg();
        setBttCotosImg();
    }

    private void setWindowIcon() {
        URL url = getClass().getResource("/logo.png");
        Image img = new ImageIcon(url).getImage();
        setIconImage(img);
    }

    private void setBttUsuarioImg() {
        URL url = getClass().getResource("/usuarioIcon.png");
        Image img = new ImageIcon(url).getImage()
                .getScaledInstance(64, 64, Image.SCALE_SMOOTH);
        bttUsuario.setIcon(new ImageIcon(img));
        bttUsuario.setHorizontalAlignment(JButton.CENTER);
    }

    private void setBttCotosImg() {
        URL url = getClass().getResource("/cotoIcon.png");
        Image img = new ImageIcon(url).getImage()
                .getScaledInstance(64, 64, Image.SCALE_SMOOTH);
        bttCotos.setIcon(new ImageIcon(img));
        bttCotos.setHorizontalAlignment(JButton.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttGroup = new javax.swing.ButtonGroup();
        jCheckBox1 = new javax.swing.JCheckBox();
        jpBtts = new javax.swing.JPanel();
        bttCotos = new javax.swing.JToggleButton();
        bttUsuario = new javax.swing.JToggleButton();
        jpMain = new javax.swing.JPanel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jpBtts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bttGroup.add(bttCotos);
        bttCotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCotosActionPerformed(evt);
            }
        });

        bttGroup.add(bttUsuario);
        bttUsuario.setSelected(true);
        bttUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBttsLayout = new javax.swing.GroupLayout(jpBtts);
        jpBtts.setLayout(jpBttsLayout);
        jpBttsLayout.setHorizontalGroup(
            jpBttsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBttsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bttUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bttCotos, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpBttsLayout.setVerticalGroup(
            jpBttsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bttCotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bttUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpMainLayout = new javax.swing.GroupLayout(jpMain);
        jpMain.setLayout(jpMainLayout);
        jpMainLayout.setHorizontalGroup(
            jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpMainLayout.setVerticalGroup(
            jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBtts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jpMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpBtts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttUsuarioActionPerformed
        if (!isCurrentPanelUsuario)
            Events.pressedUsuarioTab();
    }//GEN-LAST:event_bttUsuarioActionPerformed

    private void bttCotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCotosActionPerformed
        if (isCurrentPanelUsuario)
            Events.pressedCotosTab();
    }//GEN-LAST:event_bttCotosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bttCotos;
    private javax.swing.ButtonGroup bttGroup;
    private javax.swing.JToggleButton bttUsuario;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jpBtts;
    private javax.swing.JPanel jpMain;
    // End of variables declaration//GEN-END:variables


    public void showUsuarioPanel() {
        UsuarioPanel usuarioPanel = new UsuarioPanel(Controller.getInstance().getUsuario());
        usuarioPanel.setSize(jpMain.getSize());
        jpMain.removeAll();
        jpMain.repaint();
        jpMain.add(usuarioPanel);
        jpMain.revalidate();
        isCurrentPanelUsuario = true;
    }

    public void showCotosPanel(String matricula) {
        CotosPanel cotosPanel = new CotosPanel(Controller.getInstance().getCotos(), matricula);
        cotosPanel.setSize(jpMain.getSize());
        jpMain.removeAll();
        jpMain.repaint();
        jpMain.add(cotosPanel);
        jpMain.revalidate();
        isCurrentPanelUsuario = false;
    }

    public void setCotosBttSelected() {
        bttCotos.setSelected(true);
    }
}
