/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.gf.cotos.view;

import com.gf.cotos.entities.Usuario;

import javax.swing.*;
import java.awt.*;
import java.net.URL;

/**
 *
 * @author ismael
 */
public class UsuarioPanel extends javax.swing.JPanel {

    private final Usuario usuario;

    /**
     * Creates new form UsuarioPanel
     */
    public UsuarioPanel(Usuario usuario) {
        initComponents();
        setVisible(true);
        this.usuario = usuario;
        setUsuarioComponents();
        setLabelImg();
    }

    private void setLabelImg() {
        URL url = getClass().getResource("/bannerUsuario.png");
        System.out.println(jlImg.getWidth());
        Image img = new ImageIcon(url).getImage()
                .getScaledInstance(600, 103, Image.SCALE_SMOOTH);
        jlImg.setIcon(new ImageIcon(img));
        jlImg.setHorizontalAlignment(JLabel.CENTER);
    }

    private void setUsuarioComponents() {
        jtNIF.setText(usuario.getNif());
        jtNombre.setText(usuario.getNombre());
        jtApe1.setText(usuario.getApellido1());
        jtApe2.setText(usuario.getApellido2());
        jtTlf.setText(usuario.getTelefono());
        jtEmail.setText(usuario.getEmail());
        jtLic.setText(usuario.getLicencia());
        jtTipo.setText(usuario.getTipoLicencia());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtNIF = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtApe1 = new javax.swing.JTextField();
        jtApe2 = new javax.swing.JTextField();
        jtTlf = new javax.swing.JTextField();
        jtEmail = new javax.swing.JTextField();
        jtLic = new javax.swing.JTextField();
        jtTipo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listArrenda = new javax.swing.JList<>();
        jlNIF = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlAp1 = new javax.swing.JLabel();
        jlAp2 = new javax.swing.JLabel();
        jlTlf = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jlLicencia = new javax.swing.JLabel();
        jlTipo = new javax.swing.JLabel();
        jlArrenda = new javax.swing.JLabel();
        jpImg = new javax.swing.JPanel();
        jlImg = new javax.swing.JLabel();

        jtNIF.setEditable(false);

        jtNombre.setEditable(false);

        jtApe1.setEditable(false);

        jtApe2.setEditable(false);

        jtTlf.setEditable(false);

        jtEmail.setEditable(false);

        jtLic.setEditable(false);

        jtTipo.setEditable(false);

        jScrollPane1.setViewportView(listArrenda);

        jlNIF.setText("NIF");

        jlNombre.setText("Nombre");

        jlAp1.setText("Apellido 1");

        jlAp2.setText("Apellido2");

        jlTlf.setText("Teléfono");

        jlEmail.setText("Email");

        jlLicencia.setText("Licencia");

        jlTipo.setText("Tipo");

        jlArrenda.setText("Arrenda");

        jpImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jpImgLayout = new javax.swing.GroupLayout(jpImg);
        jpImg.setLayout(jpImgLayout);
        jpImgLayout.setHorizontalGroup(
            jpImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpImgLayout.createSequentialGroup()
                .addComponent(jlImg, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpImgLayout.setVerticalGroup(
            jpImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlImg, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jlNombre))
                            .addComponent(jlNIF, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtNIF)
                            .addComponent(jtNombre)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlAp1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtApe1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlAp2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtApe2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlArrenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jlTlf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtTlf, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlLicencia)
                            .addComponent(jlTipo)
                            .addComponent(jlEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtTipo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtLic)))
                    .addComponent(jtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNIF)
                    .addComponent(jlTlf))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNombre)
                    .addComponent(jlEmail))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtApe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtLic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAp1)
                    .addComponent(jlLicencia))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtApe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAp2)
                    .addComponent(jtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTipo))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlArrenda)
                        .addGap(38, 38, 38))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlAp1;
    private javax.swing.JLabel jlAp2;
    private javax.swing.JLabel jlArrenda;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlImg;
    private javax.swing.JLabel jlLicencia;
    private javax.swing.JLabel jlNIF;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlTipo;
    private javax.swing.JLabel jlTlf;
    private javax.swing.JPanel jpImg;
    private javax.swing.JTextField jtApe1;
    private javax.swing.JTextField jtApe2;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtLic;
    private javax.swing.JTextField jtNIF;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtTipo;
    private javax.swing.JTextField jtTlf;
    private javax.swing.JList<String> listArrenda;
    // End of variables declaration//GEN-END:variables
}
